// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DIRECT_URL"),
  },
});


// Este archivo aparecio en prisma 7
// antes las configuraciones estaban en schema.prisma
// aqui prisma sabe donde esta el schema
// cual es al URL de la DB, conexion al DB
// este archivo lo utiliza la CLI de prisma cundo se ejecutan comandos como:
// npx prisma generate, npx prima migrate dev
// lo creamos a mano