import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  auth,
  children,
}: {
  auth: React.ReactNode,
  children: React.ReactNode
}) {
  // console.log("auth:", auth);
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-dvh flex flex-col bg-gray-50">{children}{auth}</body>
      {/* <div>{auth}</div> */}
    </html>
  );
}


// Este archivo es le principal, donde se configura el doc html 
// se le puden agregar componentes globales como navbar o un footer
// 